[build]
  command = "echo 'No build needed for static site'"
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form settings
[context.production.environment]
  FORM_SUBMISSION_ENDPOINT = "/"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://www.googletagmanager.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self'"
